# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dd4b30e1a36d444004b37aa73e1dfb1061785842e6e759b92f3dc0869f51723f35bfebabe0a8c5ee88dc1cd8a37e0030116b2ce764abc8db28e2262703fb11f

test:
  secret_key_base: f5e5ac87d8945f23dda276260048a740115a60ab84842e5756ec347f082e659942fb0dcbe5bea7c3c09779fc5524759f49aa9c1666a33e6259468b47f03c0cfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
